# Generated by Django 2.1.1 on 2020-03-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
