# Generated by Django 2.1.1 on 2020-03-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20200317_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
