# Generated by Django 2.1.1 on 2020-03-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20200317_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='verified',
        ),
    ]
