# Generated by Django 2.1.1 on 2020-03-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_remove_subscriber_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='telephone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
