# Generated by Django 2.1.1 on 2020-03-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_subscriber_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='key',
        ),
    ]
