# Generated by Django 2.2.10 on 2020-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_subscriber_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='option',
            field=models.CharField(blank=True, default='none', max_length=4),
        ),
    ]
