# Generated by Django 2.2.10 on 2020-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_subscriber_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='option',
            field=models.BooleanField(default=False),
        ),
    ]
