# Generated by Django 2.2.10 on 2020-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_auto_20200319_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('recovered', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
