# Generated by Django 2.2.10 on 2020-03-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
