# Generated by Django 2.2.10 on 2020-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
