#!/bin/bash

echo " # NOTICE:
# Vue app will only detect VUE_APP_* envs
# Django
DEBUG=$DEBUG$
SECRET_KEY=$SECRET_KEY$
TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN$
BITLY_PASSWORD=$BITLY_PASSWORD$

DOMAIN=$DOMAIN$
ALLOWED_HOSTS=$ALLOWED_HOSTS$

# PostgreSQL
POSTGRES_DB=$POSTGRES_DB$
POSTGRES_PASSWORD=$POSTGRES_PASSWORD$
POSTGRES_USER=$POSTGRES_USER$

" > .env