version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "make .env file"
          command: "makeenv"
      - run:
          name: Spin up container
          command: 'docker-compose up'
      
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Spin up container
          command: 'docker-compose up -d'
      - run:
          name: Run tests
          command: |
            docker exec -it covid19_backend_1 coverage run manage.py test subscribers
            docker exec -it covid19_backend_1 coverage report
            docker exec -it covid19_backend_1 coverage html --include=apps/subscribers/"*"
      - run:
          name: Copy tests
          command: |
            docker cp covid19_backend_1:htmlcov/ /htmlcov
      - store_artifacts:
          path: /htmlcov

workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test:
          requires:
            - build
